# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b61851b990879c7c1d9e2d8f5d740d699ec45710e612f4b12a518e9cb32b6249b0f5bd56665dc315afd5340507be08e63d31a638f3a0fc78961fc377a84546f3

test:
  secret_key_base: 3bdc8eff963c2e757cdbc268e120e54ca89a3d7846c29f5740cceab4ce0bcc3302a1e6fa9dc1ab06a47dd548996efeee90580292799abcd04627a6c45682300a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
